from enum import Enum


class ParkingLibrary:
    def __init__(self):
        self.alignments = Enum("alignments", ["C", "T", "B", "L", "R"])  # => Center, Top, Bottom, Left, Right

        # ToDo : Create the dictionary for lower case letters as well
        self.possible_characters = {
            "A": {
                self.alignments.C.name: ["A", "B", "H", "F"],
                self.alignments.R.name: ["P", "R"],
            },
            "a": {
                self.alignments.C.name: ["A", "O", "0"],  # a, o, 0
                self.alignments.B.name: ["9", "Q", "G"],  # 9, q, g
                self.alignments.R.name: [],
                self.alignments.L.name: [],
                self.alignments.T.name: ["D"],  # d
            },
            "B": {
                self.alignments.C.name: [],
                self.alignments.B.name: [],
                self.alignments.R.name: [],
                self.alignments.L.name: [],
                self.alignments.T.name: [],
            },
            "C": {
                self.alignments.C.name: [],
                self.alignments.B.name: [],
                self.alignments.R.name: [],
                self.alignments.L.name: [],
                self.alignments.T.name: [],
            },
            "D": {
                self.alignments.C.name: [],
                self.alignments.B.name: [],
                self.alignments.R.name: [],
                self.alignments.L.name: [],
                self.alignments.T.name: [],
            },
            "E": {
                self.alignments.C.name: ["E"],
                self.alignments.R.name: ["B"]
            },
            "F": {
                self.alignments.C.name: ["F"],
                self.alignments.B.name: ["E"],
                self.alignments.R.name: ["A"],
            },
            "G": {
                self.alignments.C.name: [],
                self.alignments.B.name: [],
                self.alignments.R.name: [],
                self.alignments.L.name: [],
                self.alignments.T.name: [],
            },
            "H": {
                self.alignments.C.name: [],
                self.alignments.B.name: [],
                self.alignments.R.name: [],
                self.alignments.L.name: [],
                self.alignments.T.name: ["A"],
            },
            "I": {
                self.alignments.C.name: [],
                self.alignments.B.name: [],
                self.alignments.R.name: [],
                self.alignments.L.name: [],
                self.alignments.T.name: [],
            },
            "J": {
                self.alignments.C.name: [],
                self.alignments.B.name: [],
                self.alignments.R.name: [],
                self.alignments.L.name: [],
                self.alignments.T.name: [],
            },
            "K": {
                self.alignments.C.name: [],
                self.alignments.B.name: [],
                self.alignments.R.name: [],
                self.alignments.L.name: [],
                self.alignments.T.name: [],
            },
            "L": {
                self.alignments.C.name: [],
                self.alignments.B.name: [],
                self.alignments.R.name: [],
                self.alignments.L.name: [],
                self.alignments.T.name: [],
            },
            "M": {
                self.alignments.C.name: [],
                self.alignments.B.name: [],
                self.alignments.R.name: [],
                self.alignments.L.name: [],
                self.alignments.T.name: [],
            },
            "N": {
                self.alignments.C.name: ["N"],
                self.alignments.R.name: ["M"],
            },
            "O": {
                self.alignments.C.name: ["O", "0"],
                self.alignments.T.name: ["6"],
                self.alignments.B.name: ["9"],
            },
            "P": {
                self.alignments.C.name: [],
                self.alignments.B.name: [],
                self.alignments.R.name: [],
                self.alignments.L.name: [],
                self.alignments.T.name: [],
            },
            "Q": {
                self.alignments.C.name: [],
                self.alignments.B.name: [],
                self.alignments.R.name: [],
                self.alignments.L.name: [],
                self.alignments.T.name: [],
            },
            "R": {
                self.alignments.C.name: [],
                self.alignments.B.name: [],
                self.alignments.R.name: [],
                self.alignments.L.name: [],
                self.alignments.T.name: [],
            },
            "S": {
                self.alignments.C.name: [],
                self.alignments.B.name: [],
                self.alignments.R.name: [],
                self.alignments.L.name: [],
                self.alignments.T.name: [],
            },
            "T": {
                self.alignments.C.name: [],
                self.alignments.B.name: [],
                self.alignments.R.name: [],
                self.alignments.L.name: [],
                self.alignments.T.name: [],
            },
            "U": {
                self.alignments.C.name: [],
                self.alignments.B.name: [],
                self.alignments.R.name: [],
                self.alignments.L.name: [],
                self.alignments.T.name: [],
            },
            "V": {
                self.alignments.C.name: [],
                self.alignments.B.name: [],
                self.alignments.R.name: [],
                self.alignments.L.name: [],
                self.alignments.T.name: [],
            },
            "W": {
                self.alignments.C.name: [],
                self.alignments.B.name: [],
                self.alignments.R.name: [],
                self.alignments.L.name: [],
                self.alignments.T.name: [],
            },
            "X": {
                self.alignments.C.name: [],
                self.alignments.B.name: [],
                self.alignments.R.name: [],
                self.alignments.L.name: [],
                self.alignments.T.name: [],
            },
            "Y": {
                self.alignments.C.name: [],
                self.alignments.B.name: [],
                self.alignments.R.name: [],
                self.alignments.L.name: [],
                self.alignments.T.name: [],
            },
            "Z": {
                self.alignments.C.name: ["Z"]
            },
            "0": {
                self.alignments.C.name: [],
                self.alignments.B.name: [],
                self.alignments.R.name: [],
                self.alignments.L.name: [],
                self.alignments.T.name: [],
            },
            "1": {
                self.alignments.C.name: ["1", "L", "I"],
                self.alignments.B.name: ["E"],
                self.alignments.R.name: ["P", "N", "R", "M", "B", "D", "E", "F", "H", "K", "W"],
                self.alignments.L.name: ["N", "M", "W"],
                self.alignments.T.name: ["T", "Y"],
            },
            "2": {
                self.alignments.C.name: [],
                self.alignments.B.name: [],
                self.alignments.R.name: [],
                self.alignments.L.name: [],
                self.alignments.T.name: [],
            },
            "3": {
                self.alignments.C.name: [],
                self.alignments.B.name: [],
                self.alignments.R.name: [],
                self.alignments.L.name: [],
                self.alignments.T.name: [],
            },
            "4": {
                self.alignments.C.name: [],
                self.alignments.B.name: [],
                self.alignments.R.name: [],
                self.alignments.L.name: [],
                self.alignments.T.name: [],
            },
            "5": {
                self.alignments.C.name: [],
                self.alignments.B.name: [],
                self.alignments.R.name: [],
                self.alignments.L.name: [],
                self.alignments.T.name: [],
            },
            "6": {
                self.alignments.C.name: [],
                self.alignments.B.name: [],
                self.alignments.R.name: [],
                self.alignments.L.name: [],
                self.alignments.T.name: [],
            },
            "7": {
                self.alignments.C.name: ["7", "T"],
                self.alignments.B.name: ["Z"],
                self.alignments.L.name: ["N"],  # n => 7
            },
            "8": {
                self.alignments.C.name: [],
                self.alignments.B.name: [],
                self.alignments.R.name: [],
                self.alignments.L.name: [],
                self.alignments.T.name: [],
            },
            "9": {
                self.alignments.C.name: [],
                self.alignments.B.name: [],
                self.alignments.R.name: [],
                self.alignments.L.name: [],
                self.alignments.T.name: [],
            },
            ":": {
                self.alignments.C.name: [":"],
                self.alignments.B.name: [],
                self.alignments.R.name: [],
                self.alignments.L.name: [],
                self.alignments.T.name: [],
            },

        }

        self.parking_vocabulary = [
            "1",
            "1ST",
            "1AM",
            "1PM",
            "1:30AM",
            "1:30PM",
            "2",
            "2ND",
            "2AM",
            "2PM",
            "2:30AM",
            "2:30PM",
            "3",
            "3RD",
            "3AM",
            "3PM",
            "3:30AM",
            "3:30PM",
            "4",
            "4TH",
            "4AM",
            "4PM",
            "4:30AM",
            "4:30PM",
            "5",
            "5TH",
            "5AM",
            "5PM",
            "5:30AM",
            "5:30PM",
            "6",
            "6AM",
            "6PM",
            "6:30AM",
            "6:30PM",
            "7",
            "7AM",
            "7PM",
            "7:30AM",
            "7:30PM",
            "8",
            "8AM",
            "8PM",
            "8:30AM",
            "8:30PM",
            "9",
            "9AM",
            "9PM",
            "9:30AM",
            "9:30PM",
            "10",
            "10AM",
            "10PM",
            "10:30AM",
            "10:30PM",
            "11",
            "11AM",
            "11PM",
            "11:30AM",
            "11:30PM",
            "12",
            "12AM",
            "12PM",
            "12:30AM",
            "12:30PM",
            "15",
            "20",
            "30",
            "40",
            "45",
            "90",
            "AM",
            "A.M.",
            "AND",
            "AREA",
            "AWAY",
            "BLOCK",
            "CLEANING",
            "COMMERCIAL",
            "EVERYDAY",
            "EXCEPT",
            "FEDERAL",
            "FOR",
            "FRI",
            "FRIDAY",
            "HOLIDAY",
            "HOLIDAYS",
            "HOUR",
            "HOURS",
            "MINUTE",
            "MINUTES",
            "MON",
            "MONDAY",
            "MONTH",
            "NO",
            "NOTICE",
            "OF",
            "ONE",
            "ONLY",
            "PARK",
            "PARKING",
            "PAY",
            "PERMIT",
            "PERMITS",
            "PM",
            "P.M.",
            "REQUIRED",
            "SAT",
            "SATURDAY",
            "STREET",
            "STOPPING",
            "SUN",
            "SUNDAY",
            "SUNDAYS",
            "TO",
            "TOW",
            "TOWED",
            "TUE",
            "TUESDAY",
            "THE",
            "THU",
            "THURSDAY",
            "THROUGH",
            "THRU",
            "VEHICLE",
            "VEHICLES",
            "WAY",
            "WED",
            "WEDNESDAY",
            "ZONE",
        ]
